# Generated by Django 5.1.4 on 2024-12-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Blogpost',
        ),
    ]
